uktrade/enav-alpha

apps/homepage/views.py
enav_alpha/settings.py
enav_alpha/urls.py
templates/homepage.html

Create homepage template
@norm @mannickutd

Homepage template

---

.travis.yml
apps/homepage/views.py
apps/markets/models.py
apps/markets/tests/test_model.py
enav_alpha/settings.py
environment_test.sh

Added markets app with model and test.

---

templates/base.html
templates/homepage.html

Create the base template
@mannickutd @TheUKDave

create base template

---

README.md

add frontend setup to readme

---

apps/homepage/forms.py
apps/homepage/views.py
enav_alpha/urls.py
templates/homepage.html
templates/product-choice.html
templates/region-choice.html

On the homepage, choose regions. On the next page, choose product categories.
Then get filtered results.

Implement initial questions

---

templates/product-choice.html
templates/region-choice.html

@mannickutd got in just a few seconds quicker than my fixups on the last PR. :)

Use the right clearfix in the choice templates

---

apps/markets/templates/markets/list.html

/markets/ page now displays the web address of the market.

---

Procfile

Add python manage.py migrate.

---

apps/markets/templates/list.html

Hide filters.

---

apps/test/test.spec.js
gulpfile.babel.js
karma.conf.js
package.json
scripts/run_tests.sh

add javascript test framework

---

apps/assets/javascripts/results_count.js
apps/markets3/templates/markets3/filtering.html
apps/markets3/urls.py
apps/markets3/views.py
gulpfile.babel.js

On the questions page, updating any of the form inputs will cause an
ajax request for the number of matching marketplaces from the backend,
updating the count in the page.

[M3] Live update the number of matching results

---

apps/contact/apps.py
apps/contact/forms.py
apps/contact/templates/contact.html
apps/contact/tests.py
apps/contact/urls.py
apps/contact/views.py
apps/core/templates/base.html
enav_alpha/settings.py
enav_alpha/urls.py
environment_test.sh

Feedback form added with tests and working.

---

apps/markets3/templates/markets3/detail.html
apps/markets3/templates/markets3/list.html

Grey boxes updated.

---

apps/markets3/forms.py

Fixed missing import.

---

apps/assets/javascripts/main.js
apps/core/templatetags/utils.py
apps/markets2/templates/markets2/list.html

Use the filter to get regions

---

apps/markets1/templates/markets1/list.html
apps/markets2/templates/markets2/list.html
apps/markets3/templates/markets3/filtering.html
apps/markets3/templates/markets3/homepage.html
apps/markets3/templates/markets3/list.html

make page title consistent

---

apps/assets/javascripts/results_count.js

Fix result count bug on page back option.

---

apps/markets2/templates/markets2/list.html

fix icon display @norm @TheUKDave @mannickutd

Initial work done.

---

apps/assets/stylesheets/_icons.scss
apps/markets2/templates/markets2/list.html

css fixes to match design

---

apps/assets/javascripts/filter.js
apps/assets/stylesheets/_filters.scss
apps/markets3/templates/markets3/list.html

display filter options in 3 list

---

.gitignore
apps/assets/javascripts/results_count.js
apps/test/results_count.spec.js
karma.conf.js
package.json

add js test coverage task

---

apps/assets/stylesheets/_background.scss
apps/assets/stylesheets/_helpers.scss
apps/markets3/templates/markets3/detail.html

update solution 3 details page

---

apps/assets/stylesheets/_detail-page.scss
apps/markets3/templates/markets3/detail.html

update details page

---

apps/assets/stylesheets/_detail-page.scss
apps/markets3/templates/markets3/detail.html

button alignment fix
